valores = []
valores.insert(0, int(input('digite um valor: ')))
print(f'adicionando valor...')
valores.insert(1, int(input('digite outro valor: ')))
print(f'adicionando valor...')
valores.insert(2, int(input('digite um valor: ')))
print(f'adicionando valor...')
valores.insert(3, int(input('digite um valor: ')))
print(f'adicionando valor...')
valores.insert(4, int(input('digite outro valor: ')))
print(f'adicionando valor...')
print(f'foram adicionados a lista {valores}')